# Generated by Django 4.2.7 on 2025-11-02 21:33

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="任务区名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "任务区",
                "verbose_name_plural": "任务区",
                "db_table": "task_areas",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "passport_name_pinyin",
                    models.CharField(
                        blank=True,
                        help_text="护照上的姓名拼音全称",
                        max_length=200,
                        verbose_name="护照姓名拼音",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        help_text="护照号码",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="护照号码",
                    ),
                ),
                (
                    "passport_issue_date",
                    models.DateField(
                        blank=True,
                        help_text="护照签发日期",
                        null=True,
                        verbose_name="护照签发日期",
                    ),
                ),
                (
                    "passport_expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="护照到期日期",
                        null=True,
                        verbose_name="护照到期日期",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="手机号码"
                    ),
                ),
                (
                    "department_rank",
                    models.CharField(
                        blank=True,
                        help_text="部门和职别信息，自由填写",
                        max_length=100,
                        verbose_name="部门",
                    ),
                ),
                (
                    "task_area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="工作任务区域",
                        max_length=100,
                        verbose_name="任务区",
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="职位"),
                ),
                (
                    "employment_start_date",
                    models.DateField(
                        blank=True,
                        help_text="在职开始日期",
                        null=True,
                        verbose_name="在职开始时间",
                    ),
                ),
                (
                    "employment_end_date",
                    models.DateField(
                        blank=True,
                        help_text="在职结束日期（如仍在职可留空）",
                        null=True,
                        verbose_name="在职结束时间",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superuser", "超级管理员"),
                            ("head_manager", "总部负责人"),
                            ("task_area_manager", "任务区负责人"),
                            ("employee", "普通员工"),
                        ],
                        default="employee",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        help_text="当前位置纬度",
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        help_text="当前位置经度",
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "location_address",
                    models.CharField(
                        blank=True,
                        help_text="当前位置的详细地址",
                        max_length=500,
                        verbose_name="详细地址",
                    ),
                ),
                (
                    "location_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="位置更新时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "managed_task_areas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="总部负责人可管理的任务区",
                        related_name="managers",
                        to="accounts.taskarea",
                        verbose_name="管辖任务区",
                    ),
                ),
                (
                    "task_area_fk",
                    models.ForeignKey(
                        blank=True,
                        help_text="所属任务区（外键）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="accounts.taskarea",
                        verbose_name="任务区关联",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
