# Generated by Django 4.2.7 on 2025-10-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_company',
            field=models.CharField(blank=True, help_text='分配给用户的公司或分公司', max_length=100, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, help_text='当前位置纬度', null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_address',
            field=models.CharField(blank=True, help_text='当前位置的详细地址', max_length=500, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='位置更新时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, help_text='当前位置经度', null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_expiry_date',
            field=models.DateField(blank=True, help_text='护照到期日期', null=True, verbose_name='护照有效期'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_name_pinyin',
            field=models.CharField(blank=True, help_text='护照上的姓名拼音全称', max_length=200, verbose_name='护照姓名拼音'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, help_text='护照号码', max_length=50, null=True, unique=True, verbose_name='护照号码'),
        ),
    ]
