# Generated by Django 5.2.7 on 2025-10-15 16:18

from django.db import migrations


def migrate_task_areas(apps, schema_editor):
    """将现有的task_area字符串数据迁移为TaskArea外键关联"""
    User = apps.get_model('accounts', 'User')
    TaskArea = apps.get_model('accounts', 'TaskArea')
    
    # 获取所有有task_area数据的用户
    users_with_task_areas = User.objects.exclude(task_area='')
    
    for user in users_with_task_areas:
        if user.task_area:
            # 创建或获取TaskArea对象
            task_area_obj, created = TaskArea.objects.get_or_create(
                name=user.task_area,
                defaults={'description': f'从用户数据迁移的任务区：{user.task_area}'}
            )
            
            # 设置外键关联
            user.task_area_fk = task_area_obj
            user.save()
            
            if created:
                print(f"创建了新的任务区：{task_area_obj.name}")


def reverse_migrate_task_areas(apps, schema_editor):
    """反向迁移：从外键关联恢复为字符串"""
    User = apps.get_model('accounts', 'User')
    
    users_with_fk = User.objects.exclude(task_area_fk=None)
    
    for user in users_with_fk:
        if user.task_area_fk:
            user.task_area = user.task_area_fk.name
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_assigned_company_user_managed_task_areas_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_task_areas, reverse_migrate_task_areas),
    ]
