# Generated by Django 4.2.7 on 2025-10-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_task_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_rank',
            field=models.CharField(blank=True, help_text='部门和职别信息，自由填写', max_length=100, verbose_name='部门'),
        ),
    ]
