# Generated by Django 4.2.7 on 2025-10-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('place', models.CharField(max_length=200, verbose_name='休假期间所在地点')),
                ('flight_info', models.TextField(blank=True, verbose_name='往返航班信息')),
                ('emergency_contact', models.CharField(max_length=200, verbose_name='紧急联系方式')),
                ('approval_status', models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤回'), ('voided', '已作废')], default='draft', max_length=20, verbose_name='审批状态')),
                ('approval_branch_status', models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤回'), ('voided', '已作废')], default='draft', max_length=20, verbose_name='分公司审批状态')),
                ('approval_branch_date', models.DateTimeField(blank=True, null=True, verbose_name='分公司审批时间')),
                ('approval_head_status', models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤回'), ('voided', '已作废')], default='draft', max_length=20, verbose_name='总部审批状态')),
                ('approval_head_date', models.DateTimeField(blank=True, null=True, verbose_name='总部审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approval_branch_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_approvals', to=settings.AUTH_USER_MODEL, verbose_name='分公司审批人')),
                ('approval_head_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_approvals', to=settings.AUTH_USER_MODEL, verbose_name='总部审批人')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'db_table': 'leave_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
