# Generated by Django 4.2.7 on 2025-10-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_company_user_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='user',
            name='employment_end_date',
            field=models.DateField(blank=True, help_text='在职结束日期（如仍在职可留空）', null=True, verbose_name='在职结束时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_start_date',
            field=models.DateField(blank=True, help_text='在职开始日期', null=True, verbose_name='在职开始时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_issue_date',
            field=models.DateField(blank=True, help_text='护照签发日期', null=True, verbose_name='护照签发日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_expiry_date',
            field=models.DateField(blank=True, help_text='护照到期日期', null=True, verbose_name='护照到期日期'),
        ),
    ]
