# Generated by Django 5.2.7 on 2025-10-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_hire_date_user_employment_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_company',
        ),
        migrations.AddField(
            model_name='user',
            name='managed_task_areas',
            field=models.ManyToManyField(blank=True, help_text='总部负责人可管理的任务区', related_name='managers', to='accounts.taskarea', verbose_name='管辖任务区'),
        ),
        migrations.AddField(
            model_name='user',
            name='task_area_fk',
            field=models.ForeignKey(blank=True, help_text='所属任务区（外键）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.taskarea', verbose_name='任务区关联'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', '超级管理员'), ('head_manager', '总部负责人'), ('task_area_manager', '任务区负责人'), ('employee', '普通员工')], default='employee', max_length=20, verbose_name='角色'),
        ),
    ]
