# Generated by Django 4.2.7 on 2025-10-27 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('emergency', '紧急情况'), ('medical', '医疗急救'), ('security', '安全威胁'), ('location', '位置报警'), ('other', '其他')], default='emergency', max_length=20, verbose_name='报警类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('handled', '已处理'), ('resolved', '已解决'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('location_address', models.CharField(default='未知位置', max_length=500, verbose_name='地址描述')),
                ('alert_message', models.TextField(default='紧急情况报警', help_text='请详细描述紧急情况', verbose_name='报警描述')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_emergency_alerts', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handling_notes', models.TextField(blank=True, verbose_name='处理说明')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='是否已发送通知')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='通知发送时间')),
                ('alert_time', models.DateTimeField(auto_now_add=True, verbose_name='报警时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '紧急报警',
                'verbose_name_plural': '紧急报警',
                'db_table': 'emergency_alerts',
                'ordering': ['-alert_time'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, verbose_name='联系邮箱')),
                ('relationship', models.CharField(blank=True, max_length=50, verbose_name='关系')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否为主要联系人')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '紧急联系人',
                'verbose_name_plural': '紧急联系人',
                'db_table': 'emergency_contacts',
                'ordering': ['-is_primary', 'contact_name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('browser', '浏览器通知'), ('email', '邮件通知'), ('sms', '短信通知'), ('websocket', 'WebSocket通知')], max_length=20, verbose_name='通知类型')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='emergency.emergencyalert', verbose_name='关联报警')),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
