# Generated by Django 4.2.7 on 2025-10-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdownloadpackage',
            name='reports',
            field=models.ManyToManyField(related_name='bulk_download_packages', through='reports.PackageReport', to='reports.report', verbose_name='包含的报告'),
        ),
        migrations.AlterModelTable(
            name='bulkdownloadpackage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='packagereport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='report',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reportdownloadlog',
            table=None,
        ),
    ]
